- name: check registered variable for emptiness
  hosts: remote

  tasks:

  - name: List contents of directory
    ansible.builtin.command: ls /root
    register: contents

  - name: Check contents for emptiness
    ansible.builtin.debug:
      msg: "Directory is empty"
    when: contents.stdout == ""

  - name: Register a variable, ignore errors and continue
    ansible.builtin.command: /bin/false
    register: result
    ignore_errors: true

  - name: Run only if the task that registered the "result" variable fails
    ansible.builtin.command: /bin/something
    when: result is failed

  - name: Run only if the task that registered the "result" variable succeeds
    ansible.builtin.command: /bin/something_else
    when: result is succeeded

  - name: Run only if the task that registered the "result" variable is skipped
    ansible.builtin.command: /bin/still/something_else
    when: result is skipped

  - name: Run only if the task that registered the "result" variable changed something.
    ansible.builtin.command: /bin/still/something_else
    when: result is changed